In [1]:
# Importing all necessary libraries

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

# Read the Excel file

In [2]:
courses = pd.read_excel('course_recommendation.xlsx')

In [3]:
courses.head()

,courseid,title,technology,topic,abstract,url,image_url
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,NaN,https://www.datacamp.com/courses/categorical-d...,NaN
1,2,GARCH Models in R,R,Applied Finance,NaN,https://www.datacamp.com/courses/garch-models-...,NaN
2,3,Structural Equation Modeling with lavaan in R,R,Probability & Statistics,NaN,https://www.datacamp.com/courses/structural-eq...,NaN
3,4,Analyzing IoT Data in Python,Python,Data Manipulation,NaN,https://www.datacamp.com/courses/analyzing-iot...,NaN
4,5,Introduction to Spark SQL in Python,Python,Data Manipulation,NaN,https://www.datacamp.com/courses/introduction-...,NaN

#### Description of the data
## The file contains 4 features about the course which have been uploaded into our database
* title - Title of the Course
* technology - Technology of the course 
* topic - course topic
* abstract - Short summary of the course
* url - Course url - if applicable

In [4]:
# Fill the missing values with empty string

In [5]:
courses.fillna(" ",inplace=True)

In [6]:
courses.head()

,courseid,title,technology,topic,abstract,url,image_url
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,
1,2,GARCH Models in R,R,Applied Finance,,https://www.datacamp.com/courses/garch-models-...,
2,3,Structural Equation Modeling with lavaan in R,R,Probability & Statistics,,https://www.datacamp.com/courses/structural-eq...,
3,4,Analyzing IoT Data in Python,Python,Data Manipulation,,https://www.datacamp.com/courses/analyzing-iot...,
4,5,Introduction to Spark SQL in Python,Python,Data Manipulation,,https://www.datacamp.com/courses/introduction-...,

In [7]:
courses.shape

(426, 7)

In [8]:
ratings=pd.read_excel("rating.xlsx")
ratings.head()

   userid  courseid    rating
0       1       301  4.473608
1       2       301  4.696557
2       2       423  3.496996
3       2        65  4.521827
4       3       175  4.427361

In [9]:
# Filterig users who have rated more than 3 courses
x=ratings['userid'].value_counts() >3
x[x].shape

(455,)

In [10]:
# Getting indices of users who have rated more than 3 courses
y=x[x].index


# Filterig rating dataframe for users who have rated more than 3 courses

ratings=ratings[ratings['userid'].isin(y)]
ratings.head()

    userid  courseid    rating
5        4       406  3.318142
6        4       302  4.368163
7        4       289  4.244194
8        4       267  3.334461
17      10       275  4.936749

In [11]:
# Merging ratings and coursees dataframe on userid

courses_with_rating = courses.merge(ratings,on='courseid')
courses_with_rating.head()

,courseid,title,technology,topic,abstract,url,image_url,userid,rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.502358
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.185876
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.098598
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.583158
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.818197

In [12]:
courses_with_rating.shape

(2169, 9)

In [13]:
# Counting the number of ratings wrt title

num_rating = courses_with_rating.groupby('title')['rating'].count().reset_index()
num_rating.head()

                                       title  rating
0  3-Axis Machining with Autodesk Fusion 360       7
1                  3D Art and Audio Pipeline       5
2             A Crash Course in Data Science       6
3                           A/B Testing in R       5
4                           ACT Prepaaration       7

In [14]:
num_rating.shape

(424, 2)

In [15]:
# Rename rating as numbe rof rating
num_rating.rename(columns={'rating':'num_of_rating'},inplace=True)
num_rating.head()

                                       title  num_of_rating
0  3-Axis Machining with Autodesk Fusion 360              7
1                  3D Art and Audio Pipeline              5
2             A Crash Course in Data Science              6
3                           A/B Testing in R              5
4                           ACT Prepaaration              7

In [16]:
# Merging num_rating with sourses_with_rating on title 
courses_with_rating = courses_with_rating.merge(num_rating,on='title')
courses_with_rating.head()

,courseid,title,technology,topic,abstract,url,image_url,userid,rating,num_of_rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.502358,6
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.185876,6
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.098598,6
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.583158,6
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.818197,6

In [17]:
# Creating a final dataframe where number of ratings >=2
final_rating = courses_with_rating[courses_with_rating['rating']>=2]
final_rating.sample(10)
final_rating.shape

(2169, 10)

In [18]:
final_rating.drop_duplicates(['userid','title'],inplace=True)
final_rating.head()
final_rating.shape

(2160, 10)

In [19]:
final_rating.head()

,courseid,title,technology,topic,abstract,url,image_url,userid,rating,num_of_rating
0,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,224,4.502358,6
1,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,370,3.185876,6
2,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,817,3.098598,6
3,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1667,4.583158,6
4,1,Categorical Data in the Tidyverse,R,Data Manipulation,,https://www.datacamp.com/courses/categorical-d...,,1792,4.818197,6

In [20]:
# creatign a pivot table to find 
courses_pivot = final_rating.pivot(columns='userid',index='title',values='rating')
courses_pivot.head()

userid,4,10,11,16,19,21,22,29,31,32,...,1960,1965,1967,1974,1975,1977,1980,1982,1985,1990
title,,,,,,,,,,,,,,,,,,,,,
3-Axis Machining with Autodesk Fusion 360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3D Art and Audio Pipeline,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Crash Course in Data Science,4.244194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A/B Testing in R,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ACT Prepaaration,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [21]:
courses_pivot.fillna(0,inplace=True)
courses_pivot.head()

userid,4,10,11,16,19,21,22,29,31,32,...,1960,1965,1967,1974,1975,1977,1980,1982,1985,1990
title,,,,,,,,,,,,,,,,,,,,,
3-Axis Machining with Autodesk Fusion 360,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3D Art and Audio Pipeline,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Crash Course in Data Science,4.244194,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A/B Testing in R,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
ACT Prepaaration,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### To learn about Sparse Matrix
https://www.learndatasci.com/glossary/sparse-matrix/

In [22]:
from scipy.sparse import csr_matrix
courses_sparse = csr_matrix(courses_pivot)

In [34]:
print(courses_sparse)

  (0, 98)	3.1674102641619344
  (0, 106)	4.299976608363366
  (0, 124)	3.321984153448548
  (0, 216)	3.9998741930115402
  (0, 285)	4.93841455598093
  (0, 352)	4.908722545168276
  (0, 358)	3.3899653894613637
  (1, 98)	3.3542165630950245
  (1, 118)	3.569491780295447
  (1, 203)	4.864200749184263
  (1, 313)	4.925861303012724
  (1, 414)	3.7390931742257205
  (2, 0)	4.244194333833051
  (2, 38)	4.973967567865646
  (2, 146)	4.189271674610062
  (2, 197)	4.756381494911789
  (2, 265)	4.0834478629890985
  (2, 370)	3.2267354607897127
  (3, 359)	4.38245694302487
  (3, 388)	4.987325336580138
  (3, 423)	3.5919790583292617
  (3, 426)	3.12432180929765
  (3, 441)	4.081828923520637
  (4, 13)	3.120282566561313
  (4, 15)	4.6110904784549955
  :	:
  (420, 126)	4.211199905732732
  (420, 130)	3.3438863244989134
  (420, 167)	4.464543047239663
  (420, 191)	4.088753750297228
  (420, 196)	4.127191296380959
  (420, 228)	3.6025609406456844
  (420, 334)	3.540277541269509
  (420, 338)	3.097450737599044
  (420, 345)	4.168902423577733
  (420, 413)	3.9677097760632076
  (420, 416)	4.003420730382006
  (421, 64)	3.4821088334977954
  (421, 120)	4.5430798069113685
  (421, 309)	3.428189294515768
  (421, 343)	3.17631548318397
  (422, 35)	4.895616412178171
  (422, 266)	3.481889826571015
  (422, 349)	3.5438271773252983
  (422, 364)	4.165920838577397
  (422, 430)	4.994386933547691
  (423, 172)	4.532498657689734
  (423, 181)	3.2289897476564526
  (423, 194)	3.4060525713292806
  (423, 270)	4.4949735660505254
  (423, 336)	4.79365032488367

In [36]:
print(f"Indices : {courses_sparse.indices}\n")
print(f"Values  : {courses_sparse.data}\n")
print(f"Idnex Pointer  : {courses_sparse.indptr}\n")

Indices : [ 98 106 124 ... 194 270 336]

Values  : [3.16741026 4.29997661 3.32198415 ... 3.40605257 4.49497357 4.79365032]

Idnex Pointer  : [   0    7   12   18   23   30   33   37   40   41   44   51   55   58
   63   68   75   79   83   88   91   95  100  104  113  117  120  122
  128  132  136  141  142  148  154  158  162  168  170  175  180  189
  196  198  201  203  210  221  225  230  238  247  254  262  267  271
  277  281  286  290  292  294  297  304  310  314  319  325  329  335
  337  345  346  350  355  356  363  366  368  374  377  384  386  388
  394  401  403  406  412  417  423  427  431  433  438  440  444  454
  458  459  465  468  474  479  483  491  492  494  499  505  506  510
  515  520  530  535  543  549  554  562  569  574  584  588  591  593
  595  599  600  605  612  616  620  622  626  630  633  637  640  646
  649  653  658  666  668  674  681  685  686  691  698  707  712  720
  725  728  732  734  740  746  751  757  763  769  774  780  784  789
  792  799  809  817  821  830  835  838  843  848  860  865  866  876
  879  885  890  893  897  902  910  919  924  927  934  941  944  952
  958  967  970  977  981  984  991  998 1001 1005 1012 1016 1021 1028
 1034 1043 1050 1059 1063 1069 1073 1077 1083 1087 1096 1101 1109 1117
 1122 1124 1127 1133 1141 1142 1149 1152 1158 1164 1174 1180 1183 1186
 1188 1193 1198 1204 1213 1219 1223 1229 1239 1248 1251 1260 1265 1269
 1272 1276 1284 1290 1296 1302 1305 1314 1319 1322 1328 1333 1339 1347
 1352 1357 1358 1365 1367 1376 1389 1399 1402 1404 1406 1411 1415 1418
 1422 1430 1433 1438 1441 1444 1446 1451 1453 1460 1465 1470 1476 1478
 1482 1489 1495 1497 1503 1509 1512 1518 1526 1531 1534 1541 1551 1555
 1561 1567 1571 1580 1585 1593 1597 1599 1600 1605 1611 1616 1620 1625
 1629 1634 1636 1640 1643 1651 1654 1660 1666 1668 1675 1676 1682 1689
 1695 1698 1706 1715 1723 1724 1729 1730 1735 1744 1746 1750 1754 1757
 1763 1774 1780 1787 1794 1801 1806 1809 1817 1824 1830 1833 1842 1851
 1856 1862 1866 1867 1871 1876 1882 1891 1896 1899 1902 1910 1912 1917
 1921 1928 1930 1936 1940 1947 1952 1957 1961 1965 1967 1971 1978 1981
 1983 1990 1994 2000 2003 2009 2014 2020 2025 2032 2036 2040 2046 2051
 2055 2059 2065 2069 2074 2085 2090 2092 2097 2103 2112 2119 2124 2127
 2132 2146 2150 2155 2160]

In [37]:
# Model Building

from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')


# Fitting the model
model.fit(courses_sparse)

NearestNeighbors(algorithm='brute')

In [38]:
# Finding the distance and suggestion for a course with random index value

distance,suggestion = model.kneighbors(courses_pivot.iloc[15,:].values.reshape(1,-1),n_neighbors=6)

In [39]:
# Distance of all six suggested courses  with course having index 15
print(distance)
print("\n")

# Course indices of all six suggested courses  
print(suggestion)

print("\n")
# Finding the title of suggested courses

for i in range(len(suggestion)):
    print(courses_pivot.index[suggestion[i]])

[[ 0.         10.43746525 11.67643447 11.8252723  11.84313349 11.88174661]]


[[ 15 315 267 109  74   8]]


Index(['Advanced NLP with spaCy', 'Python for Spreadsheet Users',
       'Make a Game Background in Adobe Illustrator for Beginners',
       'Dimensionality Reduction in Python', 'Conda Essentials',
       'Actuarial Mathematics (also for non actuaries) Updated!'],
      dtype='object', name='title')

In [40]:
#  Storing the course names for creating the page  (for pickl file)

course_name = courses_pivot.index
course_name

Index(['3-Axis Machining with Autodesk Fusion 360',
       '3D Art and Audio Pipeline', 'A Crash Course in Data Science',
       'A/B Testing in R', 'ACT Prepaaration',
       'API Development on Google Cloud's Apigee API Platform',
       'ARIMA Modeling with R',
       'Abstraction, Problem Decomposition, and Functions',
       'Actuarial Mathematics (also for non actuaries) Updated!',
       'Adobe Illustrator: How to Draw Squared Animals Icons',
       ...
       'how to tackle cat - athira asokan, iim ahmedabad',
       'how to tackle central teacher eligibility test - ctet',
       'how to tackle gate by arvind devaraj - air 7 [i.i.sc. bangalore]',
       'how to tackle gre',
       'how to tackle ielts - rishabh varma, ielts (a - 7.5, g - 8.0)',
       'pandas Foundations', 'railway jobs in india',
       'what is post of junior scale officer of goa civil service',
       'what is rajasthan state and subordinate services combined competitive examination',
       'what is uttar pradesh public service commission combined state / upper subordinate services examination'],
      dtype='object', name='title', length=424)

In [41]:
import pickle
pickle.dump(model,open('artifacts/model.pkl','wb'))
pickle.dump(course_name,open('artifacts/course_name.pkl','wb'))
pickle.dump(courses_pivot,open('artifacts/courses_pivot.pkl','wb'))
pickle.dump(final_rating,open('artifacts/final_rating.pkl','wb'))

In [44]:
def recommend_course(course_name):
    course_id = np.where(courses_pivot.index==course_name)[0][0]
    print(course_id)
    distance,suggestion = model.kneighbors(courses_pivot.iloc[course_id,:].values.reshape(1,-1),n_neighbors=6)
    
    for i in range(len(suggestion)):
        courses = courses_pivot.index[suggestion[i]]
        for j in courses:
            print(j)
            
            
            
course_name = 'how to tackle gre'
recommend_course(course_name)

417
how to tackle gre
Make a Game Background in Adobe Illustrator for Beginners
Dimensionality Reduction in Python
Conda Essentials
Actuarial Mathematics (also for non actuaries) Updated!
Approximation Algorithms

In [43]:
recommend_course("Categorical Data in the Tidyverse")

Categorical Data in the Tidyverse
Object-Oriented Programming in Python
Financial Analytics in Spreadsheets
Make a Game Background in Adobe Illustrator for Beginners
TOEFL preparation
Supply Chain Analytics in Python

# Conclusion

## KNN method has recommended the  courses based on similar users rating